[languages]
rust = ["rustfmt"]
go = ["gofmt"]
lua = ["stylua -s -"]
# python = ["black --fast -"]
javascript = ["prettierd --parser babel"]
typescript = ["prettierd --parser typescript"]
json = ["prettierd --parser json"]
yaml = ["prettierd --parser yaml"]
sh = ["shfmt -i 2 -ci"]
toml = ["taplo fmt -"]
